/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as BookingConfirmedRouteImport } from './routes/booking-confirmed'
import { Route as FeaturesRouteImport } from './routes/features'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PricingRouteImport } from './routes/pricing'
import { Route as RobotsDottxtRouteImport } from './routes/robots[.]txt'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedScheduleRouteImport } from './routes/_authenticated/schedule'
import { Route as CheckoutIndexRouteImport } from './routes/checkout.index'
import { Route as CheckoutStartRouteImport } from './routes/checkout.start'
import { Route as CheckoutSuccessRouteImport } from './routes/checkout.success'
import { Route as ComparisonAiReceptionistVsLiveChatRouteImport } from './routes/comparison/ai-receptionist-vs-live-chat'
import { Route as ComparisonAnsweringServiceRouteImport } from './routes/comparison/answering-service'
import { Route as ComparisonPolyaiRouteImport } from './routes/comparison/polyai'
import { Route as IndustriesIndexRouteImport } from './routes/industries.index'
import { Route as IndustriesSlugRouteImport } from './routes/industries.$slug'
import { Route as InviteTokenRouteImport } from './routes/invite.$token'
import { Route as AuthenticatedAdminIndexRouteImport } from './routes/_authenticated/admin/index'
import { Route as AuthenticatedAdminAllowlistRouteImport } from './routes/_authenticated/admin/allowlist'
import { Route as AuthenticatedAdminBookingFunnelRouteImport } from './routes/_authenticated/admin/booking-funnel'
import { Route as AuthenticatedAdminCrawlDashboardRouteImport } from './routes/_authenticated/admin/crawl-dashboard'
import { Route as AuthenticatedAdminCrawlReportRouteImport } from './routes/_authenticated/admin/crawl-report'
import { Route as AuthenticatedAdminCrawlToolsRouteImport } from './routes/_authenticated/admin/crawl-tools'
import { Route as AuthenticatedAdminIndexCoverageRouteImport } from './routes/_authenticated/admin/index-coverage'
import { Route as AuthenticatedAdminIndexGapRouteImport } from './routes/_authenticated/admin/index-gap'
import { Route as AuthenticatedAdminLeadFollowupRouteImport } from './routes/_authenticated/admin/lead-followup'
import { Route as AuthenticatedAdminLeadsRouteImport } from './routes/_authenticated/admin/leads'
import { Route as AuthenticatedAdminNoindexRouteImport } from './routes/_authenticated/admin/noindex'
import { Route as AuthenticatedAdminRobotsRouteImport } from './routes/_authenticated/admin/robots'
import { Route as AuthenticatedAdminSearchConsoleRouteImport } from './routes/_authenticated/admin/search-console'
import { Route as AuthenticatedAdminSitemapRouteImport } from './routes/_authenticated/admin/sitemap'
import { Route as AuthenticatedWorkspacesBusinessIdAuditRouteImport } from './routes/_authenticated/workspaces/$businessId/audit'
import { Route as AuthenticatedWorkspacesBusinessIdCalendarRouteImport } from './routes/_authenticated/workspaces/$businessId/calendar'
import { Route as AuthenticatedWorkspacesBusinessIdMembersRouteImport } from './routes/_authenticated/workspaces/$businessId/members'
import { Route as AuthenticatedWorkspacesBusinessIdScheduleRouteImport } from './routes/_authenticated/workspaces/$businessId/schedule'
import { Route as ApiPublicHooksDailySitemapSubmitRouteImport } from './routes/api/public/hooks/daily-sitemap-submit'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'
import { Route as ApiPublicWebhooksMetaRouteImport } from './routes/api/public/webhooks/meta'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const BookingConfirmedRoute = BookingConfirmedRouteImport.update({
  id: '/booking-confirmed',
  path: '/booking-confirmed',
  getParentRoute: () => rootRouteImport,
} as any)
const FeaturesRoute = FeaturesRouteImport.update({
  id: '/features',
  path: '/features',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PricingRoute = PricingRouteImport.update({
  id: '/pricing',
  path: '/pricing',
  getParentRoute: () => rootRouteImport,
} as any)
const RobotsDottxtRoute = RobotsDottxtRouteImport.update({
  id: '/robots.txt',
  path: '/robots.txt',
  getParentRoute: () => rootRouteImport,
} as any)
const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedScheduleRoute = AuthenticatedScheduleRouteImport.update({
  id: '/schedule',
  path: '/schedule',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const CheckoutIndexRoute = CheckoutIndexRouteImport.update({
  id: '/checkout/',
  path: '/checkout/',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutStartRoute = CheckoutStartRouteImport.update({
  id: '/checkout/start',
  path: '/checkout/start',
  getParentRoute: () => rootRouteImport,
} as any)
const CheckoutSuccessRoute = CheckoutSuccessRouteImport.update({
  id: '/checkout/success',
  path: '/checkout/success',
  getParentRoute: () => rootRouteImport,
} as any)
const ComparisonAiReceptionistVsLiveChatRoute =
  ComparisonAiReceptionistVsLiveChatRouteImport.update({
    id: '/comparison/ai-receptionist-vs-live-chat',
    path: '/comparison/ai-receptionist-vs-live-chat',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComparisonAnsweringServiceRoute =
  ComparisonAnsweringServiceRouteImport.update({
    id: '/comparison/answering-service',
    path: '/comparison/answering-service',
    getParentRoute: () => rootRouteImport,
  } as any)
const ComparisonPolyaiRoute = ComparisonPolyaiRouteImport.update({
  id: '/comparison/polyai',
  path: '/comparison/polyai',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesIndexRoute = IndustriesIndexRouteImport.update({
  id: '/industries/',
  path: '/industries/',
  getParentRoute: () => rootRouteImport,
} as any)
const IndustriesSlugRoute = IndustriesSlugRouteImport.update({
  id: '/industries/$slug',
  path: '/industries/$slug',
  getParentRoute: () => rootRouteImport,
} as any)
const InviteTokenRoute = InviteTokenRouteImport.update({
  id: '/invite/$token',
  path: '/invite/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedAdminIndexRoute = AuthenticatedAdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminAllowlistRoute =
  AuthenticatedAdminAllowlistRouteImport.update({
    id: '/admin/allowlist',
    path: '/admin/allowlist',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminBookingFunnelRoute =
  AuthenticatedAdminBookingFunnelRouteImport.update({
    id: '/admin/booking-funnel',
    path: '/admin/booking-funnel',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCrawlDashboardRoute =
  AuthenticatedAdminCrawlDashboardRouteImport.update({
    id: '/admin/crawl-dashboard',
    path: '/admin/crawl-dashboard',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCrawlReportRoute =
  AuthenticatedAdminCrawlReportRouteImport.update({
    id: '/admin/crawl-report',
    path: '/admin/crawl-report',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminCrawlToolsRoute =
  AuthenticatedAdminCrawlToolsRouteImport.update({
    id: '/admin/crawl-tools',
    path: '/admin/crawl-tools',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexCoverageRoute =
  AuthenticatedAdminIndexCoverageRouteImport.update({
    id: '/admin/index-coverage',
    path: '/admin/index-coverage',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminIndexGapRoute =
  AuthenticatedAdminIndexGapRouteImport.update({
    id: '/admin/index-gap',
    path: '/admin/index-gap',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLeadFollowupRoute =
  AuthenticatedAdminLeadFollowupRouteImport.update({
    id: '/admin/lead-followup',
    path: '/admin/lead-followup',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminLeadsRoute = AuthenticatedAdminLeadsRouteImport.update({
  id: '/admin/leads',
  path: '/admin/leads',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminNoindexRoute =
  AuthenticatedAdminNoindexRouteImport.update({
    id: '/admin/noindex',
    path: '/admin/noindex',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminRobotsRoute =
  AuthenticatedAdminRobotsRouteImport.update({
    id: '/admin/robots',
    path: '/admin/robots',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSearchConsoleRoute =
  AuthenticatedAdminSearchConsoleRouteImport.update({
    id: '/admin/search-console',
    path: '/admin/search-console',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminSitemapRoute =
  AuthenticatedAdminSitemapRouteImport.update({
    id: '/admin/sitemap',
    path: '/admin/sitemap',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesBusinessIdAuditRoute =
  AuthenticatedWorkspacesBusinessIdAuditRouteImport.update({
    id: '/workspaces/$businessId/audit',
    path: '/workspaces/$businessId/audit',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesBusinessIdCalendarRoute =
  AuthenticatedWorkspacesBusinessIdCalendarRouteImport.update({
    id: '/workspaces/$businessId/calendar',
    path: '/workspaces/$businessId/calendar',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesBusinessIdMembersRoute =
  AuthenticatedWorkspacesBusinessIdMembersRouteImport.update({
    id: '/workspaces/$businessId/members',
    path: '/workspaces/$businessId/members',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedWorkspacesBusinessIdScheduleRoute =
  AuthenticatedWorkspacesBusinessIdScheduleRouteImport.update({
    id: '/workspaces/$businessId/schedule',
    path: '/workspaces/$businessId/schedule',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const ApiPublicHooksDailySitemapSubmitRoute =
  ApiPublicHooksDailySitemapSubmitRouteImport.update({
    id: '/api/public/hooks/daily-sitemap-submit',
    path: '/api/public/hooks/daily-sitemap-submit',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicWebhooksMetaRoute = ApiPublicWebhooksMetaRouteImport.update({
  id: '/api/public/webhooks/meta',
  path: '/api/public/webhooks/meta',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/checkout/start': typeof CheckoutStartRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/comparison/ai-receptionist-vs-live-chat': typeof ComparisonAiReceptionistVsLiveChatRoute
  '/comparison/answering-service': typeof ComparisonAnsweringServiceRoute
  '/comparison/polyai': typeof ComparisonPolyaiRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/admin/allowlist': typeof AuthenticatedAdminAllowlistRoute
  '/admin/booking-funnel': typeof AuthenticatedAdminBookingFunnelRoute
  '/admin/crawl-dashboard': typeof AuthenticatedAdminCrawlDashboardRoute
  '/admin/crawl-report': typeof AuthenticatedAdminCrawlReportRoute
  '/admin/crawl-tools': typeof AuthenticatedAdminCrawlToolsRoute
  '/admin/index-coverage': typeof AuthenticatedAdminIndexCoverageRoute
  '/admin/index-gap': typeof AuthenticatedAdminIndexGapRoute
  '/admin/lead-followup': typeof AuthenticatedAdminLeadFollowupRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/noindex': typeof AuthenticatedAdminNoindexRoute
  '/admin/robots': typeof AuthenticatedAdminRobotsRoute
  '/admin/search-console': typeof AuthenticatedAdminSearchConsoleRoute
  '/admin/sitemap': typeof AuthenticatedAdminSitemapRoute
  '/admin/': typeof AuthenticatedAdminIndexRoute
  '/workspaces/$businessId/audit': typeof AuthenticatedWorkspacesBusinessIdAuditRoute
  '/workspaces/$businessId/calendar': typeof AuthenticatedWorkspacesBusinessIdCalendarRoute
  '/workspaces/$businessId/members': typeof AuthenticatedWorkspacesBusinessIdMembersRoute
  '/workspaces/$businessId/schedule': typeof AuthenticatedWorkspacesBusinessIdScheduleRoute
  '/api/public/hooks/daily-sitemap-submit': typeof ApiPublicHooksDailySitemapSubmitRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/webhooks/meta': typeof ApiPublicWebhooksMetaRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/schedule': typeof AuthenticatedScheduleRoute
  '/checkout/start': typeof CheckoutStartRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/comparison/ai-receptionist-vs-live-chat': typeof ComparisonAiReceptionistVsLiveChatRoute
  '/comparison/answering-service': typeof ComparisonAnsweringServiceRoute
  '/comparison/polyai': typeof ComparisonPolyaiRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/checkout': typeof CheckoutIndexRoute
  '/industries': typeof IndustriesIndexRoute
  '/admin/allowlist': typeof AuthenticatedAdminAllowlistRoute
  '/admin/booking-funnel': typeof AuthenticatedAdminBookingFunnelRoute
  '/admin/crawl-dashboard': typeof AuthenticatedAdminCrawlDashboardRoute
  '/admin/crawl-report': typeof AuthenticatedAdminCrawlReportRoute
  '/admin/crawl-tools': typeof AuthenticatedAdminCrawlToolsRoute
  '/admin/index-coverage': typeof AuthenticatedAdminIndexCoverageRoute
  '/admin/index-gap': typeof AuthenticatedAdminIndexGapRoute
  '/admin/lead-followup': typeof AuthenticatedAdminLeadFollowupRoute
  '/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/admin/noindex': typeof AuthenticatedAdminNoindexRoute
  '/admin/robots': typeof AuthenticatedAdminRobotsRoute
  '/admin/search-console': typeof AuthenticatedAdminSearchConsoleRoute
  '/admin/sitemap': typeof AuthenticatedAdminSitemapRoute
  '/admin': typeof AuthenticatedAdminIndexRoute
  '/workspaces/$businessId/audit': typeof AuthenticatedWorkspacesBusinessIdAuditRoute
  '/workspaces/$businessId/calendar': typeof AuthenticatedWorkspacesBusinessIdCalendarRoute
  '/workspaces/$businessId/members': typeof AuthenticatedWorkspacesBusinessIdMembersRoute
  '/workspaces/$businessId/schedule': typeof AuthenticatedWorkspacesBusinessIdScheduleRoute
  '/api/public/hooks/daily-sitemap-submit': typeof ApiPublicHooksDailySitemapSubmitRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/webhooks/meta': typeof ApiPublicWebhooksMetaRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/booking-confirmed': typeof BookingConfirmedRoute
  '/features': typeof FeaturesRoute
  '/login': typeof LoginRoute
  '/pricing': typeof PricingRoute
  '/robots.txt': typeof RobotsDottxtRoute
  '/signup': typeof SignupRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/schedule': typeof AuthenticatedScheduleRoute
  '/checkout/start': typeof CheckoutStartRoute
  '/checkout/success': typeof CheckoutSuccessRoute
  '/comparison/ai-receptionist-vs-live-chat': typeof ComparisonAiReceptionistVsLiveChatRoute
  '/comparison/answering-service': typeof ComparisonAnsweringServiceRoute
  '/comparison/polyai': typeof ComparisonPolyaiRoute
  '/industries/$slug': typeof IndustriesSlugRoute
  '/invite/$token': typeof InviteTokenRoute
  '/checkout/': typeof CheckoutIndexRoute
  '/industries/': typeof IndustriesIndexRoute
  '/_authenticated/admin/allowlist': typeof AuthenticatedAdminAllowlistRoute
  '/_authenticated/admin/booking-funnel': typeof AuthenticatedAdminBookingFunnelRoute
  '/_authenticated/admin/crawl-dashboard': typeof AuthenticatedAdminCrawlDashboardRoute
  '/_authenticated/admin/crawl-report': typeof AuthenticatedAdminCrawlReportRoute
  '/_authenticated/admin/crawl-tools': typeof AuthenticatedAdminCrawlToolsRoute
  '/_authenticated/admin/index-coverage': typeof AuthenticatedAdminIndexCoverageRoute
  '/_authenticated/admin/index-gap': typeof AuthenticatedAdminIndexGapRoute
  '/_authenticated/admin/lead-followup': typeof AuthenticatedAdminLeadFollowupRoute
  '/_authenticated/admin/leads': typeof AuthenticatedAdminLeadsRoute
  '/_authenticated/admin/noindex': typeof AuthenticatedAdminNoindexRoute
  '/_authenticated/admin/robots': typeof AuthenticatedAdminRobotsRoute
  '/_authenticated/admin/search-console': typeof AuthenticatedAdminSearchConsoleRoute
  '/_authenticated/admin/sitemap': typeof AuthenticatedAdminSitemapRoute
  '/_authenticated/admin/': typeof AuthenticatedAdminIndexRoute
  '/_authenticated/workspaces/$businessId/audit': typeof AuthenticatedWorkspacesBusinessIdAuditRoute
  '/_authenticated/workspaces/$businessId/calendar': typeof AuthenticatedWorkspacesBusinessIdCalendarRoute
  '/_authenticated/workspaces/$businessId/members': typeof AuthenticatedWorkspacesBusinessIdMembersRoute
  '/_authenticated/workspaces/$businessId/schedule': typeof AuthenticatedWorkspacesBusinessIdScheduleRoute
  '/api/public/hooks/daily-sitemap-submit': typeof ApiPublicHooksDailySitemapSubmitRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
  '/api/public/webhooks/meta': typeof ApiPublicWebhooksMetaRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/booking-confirmed'
    | '/features'
    | '/login'
    | '/pricing'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/dashboard'
    | '/schedule'
    | '/checkout/start'
    | '/checkout/success'
    | '/comparison/ai-receptionist-vs-live-chat'
    | '/comparison/answering-service'
    | '/comparison/polyai'
    | '/industries/$slug'
    | '/invite/$token'
    | '/checkout/'
    | '/industries/'
    | '/admin/allowlist'
    | '/admin/booking-funnel'
    | '/admin/crawl-dashboard'
    | '/admin/crawl-report'
    | '/admin/crawl-tools'
    | '/admin/index-coverage'
    | '/admin/index-gap'
    | '/admin/lead-followup'
    | '/admin/leads'
    | '/admin/noindex'
    | '/admin/robots'
    | '/admin/search-console'
    | '/admin/sitemap'
    | '/admin/'
    | '/workspaces/$businessId/audit'
    | '/workspaces/$businessId/calendar'
    | '/workspaces/$businessId/members'
    | '/workspaces/$businessId/schedule'
    | '/api/public/hooks/daily-sitemap-submit'
    | '/api/public/payments/webhook'
    | '/api/public/webhooks/meta'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/booking-confirmed'
    | '/features'
    | '/login'
    | '/pricing'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/dashboard'
    | '/schedule'
    | '/checkout/start'
    | '/checkout/success'
    | '/comparison/ai-receptionist-vs-live-chat'
    | '/comparison/answering-service'
    | '/comparison/polyai'
    | '/industries/$slug'
    | '/invite/$token'
    | '/checkout'
    | '/industries'
    | '/admin/allowlist'
    | '/admin/booking-funnel'
    | '/admin/crawl-dashboard'
    | '/admin/crawl-report'
    | '/admin/crawl-tools'
    | '/admin/index-coverage'
    | '/admin/index-gap'
    | '/admin/lead-followup'
    | '/admin/leads'
    | '/admin/noindex'
    | '/admin/robots'
    | '/admin/search-console'
    | '/admin/sitemap'
    | '/admin'
    | '/workspaces/$businessId/audit'
    | '/workspaces/$businessId/calendar'
    | '/workspaces/$businessId/members'
    | '/workspaces/$businessId/schedule'
    | '/api/public/hooks/daily-sitemap-submit'
    | '/api/public/payments/webhook'
    | '/api/public/webhooks/meta'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/booking-confirmed'
    | '/features'
    | '/login'
    | '/pricing'
    | '/robots.txt'
    | '/signup'
    | '/sitemap.xml'
    | '/_authenticated/dashboard'
    | '/_authenticated/schedule'
    | '/checkout/start'
    | '/checkout/success'
    | '/comparison/ai-receptionist-vs-live-chat'
    | '/comparison/answering-service'
    | '/comparison/polyai'
    | '/industries/$slug'
    | '/invite/$token'
    | '/checkout/'
    | '/industries/'
    | '/_authenticated/admin/allowlist'
    | '/_authenticated/admin/booking-funnel'
    | '/_authenticated/admin/crawl-dashboard'
    | '/_authenticated/admin/crawl-report'
    | '/_authenticated/admin/crawl-tools'
    | '/_authenticated/admin/index-coverage'
    | '/_authenticated/admin/index-gap'
    | '/_authenticated/admin/lead-followup'
    | '/_authenticated/admin/leads'
    | '/_authenticated/admin/noindex'
    | '/_authenticated/admin/robots'
    | '/_authenticated/admin/search-console'
    | '/_authenticated/admin/sitemap'
    | '/_authenticated/admin/'
    | '/_authenticated/workspaces/$businessId/audit'
    | '/_authenticated/workspaces/$businessId/calendar'
    | '/_authenticated/workspaces/$businessId/members'
    | '/_authenticated/workspaces/$businessId/schedule'
    | '/api/public/hooks/daily-sitemap-submit'
    | '/api/public/payments/webhook'
    | '/api/public/webhooks/meta'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  BookingConfirmedRoute: typeof BookingConfirmedRoute
  FeaturesRoute: typeof FeaturesRoute
  LoginRoute: typeof LoginRoute
  PricingRoute: typeof PricingRoute
  RobotsDottxtRoute: typeof RobotsDottxtRoute
  SignupRoute: typeof SignupRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
  CheckoutStartRoute: typeof CheckoutStartRoute
  CheckoutSuccessRoute: typeof CheckoutSuccessRoute
  ComparisonAiReceptionistVsLiveChatRoute: typeof ComparisonAiReceptionistVsLiveChatRoute
  ComparisonAnsweringServiceRoute: typeof ComparisonAnsweringServiceRoute
  ComparisonPolyaiRoute: typeof ComparisonPolyaiRoute
  IndustriesSlugRoute: typeof IndustriesSlugRoute
  InviteTokenRoute: typeof InviteTokenRoute
  CheckoutIndexRoute: typeof CheckoutIndexRoute
  IndustriesIndexRoute: typeof IndustriesIndexRoute
  ApiPublicHooksDailySitemapSubmitRoute: typeof ApiPublicHooksDailySitemapSubmitRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
  ApiPublicWebhooksMetaRoute: typeof ApiPublicWebhooksMetaRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/booking-confirmed': {
      id: '/booking-confirmed'
      path: '/booking-confirmed'
      fullPath: '/booking-confirmed'
      preLoaderRoute: typeof BookingConfirmedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/features': {
      id: '/features'
      path: '/features'
      fullPath: '/features'
      preLoaderRoute: typeof FeaturesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pricing': {
      id: '/pricing'
      path: '/pricing'
      fullPath: '/pricing'
      preLoaderRoute: typeof PricingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/robots.txt': {
      id: '/robots.txt'
      path: '/robots.txt'
      fullPath: '/robots.txt'
      preLoaderRoute: typeof RobotsDottxtRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/schedule': {
      id: '/_authenticated/schedule'
      path: '/schedule'
      fullPath: '/schedule'
      preLoaderRoute: typeof AuthenticatedScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/checkout/': {
      id: '/checkout/'
      path: '/checkout'
      fullPath: '/checkout/'
      preLoaderRoute: typeof CheckoutIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/start': {
      id: '/checkout/start'
      path: '/checkout/start'
      fullPath: '/checkout/start'
      preLoaderRoute: typeof CheckoutStartRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/checkout/success': {
      id: '/checkout/success'
      path: '/checkout/success'
      fullPath: '/checkout/success'
      preLoaderRoute: typeof CheckoutSuccessRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison/ai-receptionist-vs-live-chat': {
      id: '/comparison/ai-receptionist-vs-live-chat'
      path: '/comparison/ai-receptionist-vs-live-chat'
      fullPath: '/comparison/ai-receptionist-vs-live-chat'
      preLoaderRoute: typeof ComparisonAiReceptionistVsLiveChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison/answering-service': {
      id: '/comparison/answering-service'
      path: '/comparison/answering-service'
      fullPath: '/comparison/answering-service'
      preLoaderRoute: typeof ComparisonAnsweringServiceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/comparison/polyai': {
      id: '/comparison/polyai'
      path: '/comparison/polyai'
      fullPath: '/comparison/polyai'
      preLoaderRoute: typeof ComparisonPolyaiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/': {
      id: '/industries/'
      path: '/industries'
      fullPath: '/industries/'
      preLoaderRoute: typeof IndustriesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/industries/$slug': {
      id: '/industries/$slug'
      path: '/industries/$slug'
      fullPath: '/industries/$slug'
      preLoaderRoute: typeof IndustriesSlugRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/invite/$token': {
      id: '/invite/$token'
      path: '/invite/$token'
      fullPath: '/invite/$token'
      preLoaderRoute: typeof InviteTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/': {
      id: '/_authenticated/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AuthenticatedAdminIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/allowlist': {
      id: '/_authenticated/admin/allowlist'
      path: '/admin/allowlist'
      fullPath: '/admin/allowlist'
      preLoaderRoute: typeof AuthenticatedAdminAllowlistRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/booking-funnel': {
      id: '/_authenticated/admin/booking-funnel'
      path: '/admin/booking-funnel'
      fullPath: '/admin/booking-funnel'
      preLoaderRoute: typeof AuthenticatedAdminBookingFunnelRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/crawl-dashboard': {
      id: '/_authenticated/admin/crawl-dashboard'
      path: '/admin/crawl-dashboard'
      fullPath: '/admin/crawl-dashboard'
      preLoaderRoute: typeof AuthenticatedAdminCrawlDashboardRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/crawl-report': {
      id: '/_authenticated/admin/crawl-report'
      path: '/admin/crawl-report'
      fullPath: '/admin/crawl-report'
      preLoaderRoute: typeof AuthenticatedAdminCrawlReportRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/crawl-tools': {
      id: '/_authenticated/admin/crawl-tools'
      path: '/admin/crawl-tools'
      fullPath: '/admin/crawl-tools'
      preLoaderRoute: typeof AuthenticatedAdminCrawlToolsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/index-coverage': {
      id: '/_authenticated/admin/index-coverage'
      path: '/admin/index-coverage'
      fullPath: '/admin/index-coverage'
      preLoaderRoute: typeof AuthenticatedAdminIndexCoverageRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/index-gap': {
      id: '/_authenticated/admin/index-gap'
      path: '/admin/index-gap'
      fullPath: '/admin/index-gap'
      preLoaderRoute: typeof AuthenticatedAdminIndexGapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/lead-followup': {
      id: '/_authenticated/admin/lead-followup'
      path: '/admin/lead-followup'
      fullPath: '/admin/lead-followup'
      preLoaderRoute: typeof AuthenticatedAdminLeadFollowupRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/leads': {
      id: '/_authenticated/admin/leads'
      path: '/admin/leads'
      fullPath: '/admin/leads'
      preLoaderRoute: typeof AuthenticatedAdminLeadsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/noindex': {
      id: '/_authenticated/admin/noindex'
      path: '/admin/noindex'
      fullPath: '/admin/noindex'
      preLoaderRoute: typeof AuthenticatedAdminNoindexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/robots': {
      id: '/_authenticated/admin/robots'
      path: '/admin/robots'
      fullPath: '/admin/robots'
      preLoaderRoute: typeof AuthenticatedAdminRobotsRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/search-console': {
      id: '/_authenticated/admin/search-console'
      path: '/admin/search-console'
      fullPath: '/admin/search-console'
      preLoaderRoute: typeof AuthenticatedAdminSearchConsoleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/sitemap': {
      id: '/_authenticated/admin/sitemap'
      path: '/admin/sitemap'
      fullPath: '/admin/sitemap'
      preLoaderRoute: typeof AuthenticatedAdminSitemapRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$businessId/audit': {
      id: '/_authenticated/workspaces/$businessId/audit'
      path: '/workspaces/$businessId/audit'
      fullPath: '/workspaces/$businessId/audit'
      preLoaderRoute: typeof AuthenticatedWorkspacesBusinessIdAuditRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$businessId/calendar': {
      id: '/_authenticated/workspaces/$businessId/calendar'
      path: '/workspaces/$businessId/calendar'
      fullPath: '/workspaces/$businessId/calendar'
      preLoaderRoute: typeof AuthenticatedWorkspacesBusinessIdCalendarRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$businessId/members': {
      id: '/_authenticated/workspaces/$businessId/members'
      path: '/workspaces/$businessId/members'
      fullPath: '/workspaces/$businessId/members'
      preLoaderRoute: typeof AuthenticatedWorkspacesBusinessIdMembersRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/workspaces/$businessId/schedule': {
      id: '/_authenticated/workspaces/$businessId/schedule'
      path: '/workspaces/$businessId/schedule'
      fullPath: '/workspaces/$businessId/schedule'
      preLoaderRoute: typeof AuthenticatedWorkspacesBusinessIdScheduleRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/api/public/hooks/daily-sitemap-submit': {
      id: '/api/public/hooks/daily-sitemap-submit'
      path: '/api/public/hooks/daily-sitemap-submit'
      fullPath: '/api/public/hooks/daily-sitemap-submit'
      preLoaderRoute: typeof ApiPublicHooksDailySitemapSubmitRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/webhooks/meta': {
      id: '/api/public/webhooks/meta'
      path: '/api/public/webhooks/meta'
      fullPath: '/api/public/webhooks/meta'
      preLoaderRoute: typeof ApiPublicWebhooksMetaRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedRouteChildren {
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedScheduleRoute: typeof AuthenticatedScheduleRoute
  AuthenticatedAdminAllowlistRoute: typeof AuthenticatedAdminAllowlistRoute
  AuthenticatedAdminBookingFunnelRoute: typeof AuthenticatedAdminBookingFunnelRoute
  AuthenticatedAdminCrawlDashboardRoute: typeof AuthenticatedAdminCrawlDashboardRoute
  AuthenticatedAdminCrawlReportRoute: typeof AuthenticatedAdminCrawlReportRoute
  AuthenticatedAdminCrawlToolsRoute: typeof AuthenticatedAdminCrawlToolsRoute
  AuthenticatedAdminIndexCoverageRoute: typeof AuthenticatedAdminIndexCoverageRoute
  AuthenticatedAdminIndexGapRoute: typeof AuthenticatedAdminIndexGapRoute
  AuthenticatedAdminLeadFollowupRoute: typeof AuthenticatedAdminLeadFollowupRoute
  AuthenticatedAdminLeadsRoute: typeof AuthenticatedAdminLeadsRoute
  AuthenticatedAdminNoindexRoute: typeof AuthenticatedAdminNoindexRoute
  AuthenticatedAdminRobotsRoute: typeof AuthenticatedAdminRobotsRoute
  AuthenticatedAdminSearchConsoleRoute: typeof AuthenticatedAdminSearchConsoleRoute
  AuthenticatedAdminSitemapRoute: typeof AuthenticatedAdminSitemapRoute
  AuthenticatedAdminIndexRoute: typeof AuthenticatedAdminIndexRoute
  AuthenticatedWorkspacesBusinessIdAuditRoute: typeof AuthenticatedWorkspacesBusinessIdAuditRoute
  AuthenticatedWorkspacesBusinessIdCalendarRoute: typeof AuthenticatedWorkspacesBusinessIdCalendarRoute
  AuthenticatedWorkspacesBusinessIdMembersRoute: typeof AuthenticatedWorkspacesBusinessIdMembersRoute
  AuthenticatedWorkspacesBusinessIdScheduleRoute: typeof AuthenticatedWorkspacesBusinessIdScheduleRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedScheduleRoute: AuthenticatedScheduleRoute,
  AuthenticatedAdminAllowlistRoute: AuthenticatedAdminAllowlistRoute,
  AuthenticatedAdminBookingFunnelRoute: AuthenticatedAdminBookingFunnelRoute,
  AuthenticatedAdminCrawlDashboardRoute: AuthenticatedAdminCrawlDashboardRoute,
  AuthenticatedAdminCrawlReportRoute: AuthenticatedAdminCrawlReportRoute,
  AuthenticatedAdminCrawlToolsRoute: AuthenticatedAdminCrawlToolsRoute,
  AuthenticatedAdminIndexCoverageRoute: AuthenticatedAdminIndexCoverageRoute,
  AuthenticatedAdminIndexGapRoute: AuthenticatedAdminIndexGapRoute,
  AuthenticatedAdminLeadFollowupRoute: AuthenticatedAdminLeadFollowupRoute,
  AuthenticatedAdminLeadsRoute: AuthenticatedAdminLeadsRoute,
  AuthenticatedAdminNoindexRoute: AuthenticatedAdminNoindexRoute,
  AuthenticatedAdminRobotsRoute: AuthenticatedAdminRobotsRoute,
  AuthenticatedAdminSearchConsoleRoute: AuthenticatedAdminSearchConsoleRoute,
  AuthenticatedAdminSitemapRoute: AuthenticatedAdminSitemapRoute,
  AuthenticatedAdminIndexRoute: AuthenticatedAdminIndexRoute,
  AuthenticatedWorkspacesBusinessIdAuditRoute:
    AuthenticatedWorkspacesBusinessIdAuditRoute,
  AuthenticatedWorkspacesBusinessIdCalendarRoute:
    AuthenticatedWorkspacesBusinessIdCalendarRoute,
  AuthenticatedWorkspacesBusinessIdMembersRoute:
    AuthenticatedWorkspacesBusinessIdMembersRoute,
  AuthenticatedWorkspacesBusinessIdScheduleRoute:
    AuthenticatedWorkspacesBusinessIdScheduleRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  BookingConfirmedRoute: BookingConfirmedRoute,
  FeaturesRoute: FeaturesRoute,
  LoginRoute: LoginRoute,
  PricingRoute: PricingRoute,
  RobotsDottxtRoute: RobotsDottxtRoute,
  SignupRoute: SignupRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
  CheckoutStartRoute: CheckoutStartRoute,
  CheckoutSuccessRoute: CheckoutSuccessRoute,
  ComparisonAiReceptionistVsLiveChatRoute:
    ComparisonAiReceptionistVsLiveChatRoute,
  ComparisonAnsweringServiceRoute: ComparisonAnsweringServiceRoute,
  ComparisonPolyaiRoute: ComparisonPolyaiRoute,
  IndustriesSlugRoute: IndustriesSlugRoute,
  InviteTokenRoute: InviteTokenRoute,
  CheckoutIndexRoute: CheckoutIndexRoute,
  IndustriesIndexRoute: IndustriesIndexRoute,
  ApiPublicHooksDailySitemapSubmitRoute: ApiPublicHooksDailySitemapSubmitRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
  ApiPublicWebhooksMetaRoute: ApiPublicWebhooksMetaRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
